/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.common.gui {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.common.gui.LocationGroup$STATE")]
    public class LocationGroup$STATE extends Enum {

        public static const AVAILABLE:LocationGroup$STATE = new LocationGroup$STATE("AVAILABLE", _);
        public static const NOT_AVAILABLE:LocationGroup$STATE = new LocationGroup$STATE("NOT_AVAILABLE", _);

        function LocationGroup$STATE(value:String = null, restrictor:* = null) {
            super((value || AVAILABLE.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [AVAILABLE, NOT_AVAILABLE];
        }

        public static function valueOf(name:String):LocationGroup$STATE {
        	return LocationGroup$STATE(AVAILABLE.constantOf(name));
        }
    }
}