/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.tms.domain.order {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.tms.domain.order.TransportOrder$TRANSPORT_ORDER_STATE")]
    public class TransportOrder$TRANSPORT_ORDER_STATE extends Enum {

        public static const CREATED:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("CREATED", _);
        public static const INITIALIZED:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("INITIALIZED", _);
        public static const STARTED:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("STARTED", _);
        public static const INTERRUPTED:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("INTERRUPTED", _);
        public static const ONFAILURE:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("ONFAILURE", _);
        public static const FINISHED:TransportOrder$TRANSPORT_ORDER_STATE = new TransportOrder$TRANSPORT_ORDER_STATE("FINISHED", _);

        function TransportOrder$TRANSPORT_ORDER_STATE(value:String = null, restrictor:* = null) {
            super((value || CREATED.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CREATED, INITIALIZED, STARTED, INTERRUPTED, ONFAILURE, FINISHED];
        }

        public static function valueOf(name:String):TransportOrder$TRANSPORT_ORDER_STATE {
            return TransportOrder$TRANSPORT_ORDER_STATE(CREATED.constantOf(name));
        }
    }
}