/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.common.domain.values {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.common.domain.values.WeightUnit")]
    public class WeightUnit extends Enum {

        public static const MG:WeightUnit = new WeightUnit("MG", _);
        public static const G:WeightUnit = new WeightUnit("G", _);
        public static const KG:WeightUnit = new WeightUnit("KG", _);
        public static const T:WeightUnit = new WeightUnit("T", _);

        function WeightUnit(value:String = null, restrictor:* = null) {
            super((value || MG.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [MG, G, KG, T];
        }

        public static function valueOf(name:String):WeightUnit {
        	return WeightUnit(MG.constantOf(name));
        }
    }
}