/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Weight.as).
 */

package org.openwms.common.domain.values {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.util.Enum;

    [Bindable]
    public class WeightBase implements IExternalizable, Unit {

        private var _unit:WeightUnit;
        private var _value:Number;

        public function get unit():WeightUnit {
            return _unit;
        }

        public function get value():Number {
            return _value;
        }

        public function readExternal(input:IDataInput):void {
            _unit = Enum.readEnum(input) as WeightUnit;
            _value = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_unit);
            output.writeObject(_value);
        }
    }
}