/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TreeNodeImpl.as).
 */

package org.openwms.common.util {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IMap;

    [Bindable]
    public class TreeNodeImplBase implements IExternalizable, TreeNode {

        private var _childrenMap:IMap;
        private var _data:Object;
        private var _parent:TreeNode;

        public function set data(value:Object):void {
            _data = value;
        }
        public function get data():Object {
            return _data;
        }

        public function set parent(value:TreeNode):void {
            _parent = value;
        }
        public function get parent():TreeNode {
            return _parent;
        }

        public function get children():Iterator {
            return null;
        }

        public function get leaf():Boolean {
            return false;
        }

        public function readExternal(input:IDataInput):void {
            _childrenMap = input.readObject() as IMap;
            _data = input.readObject() as Object;
            _parent = input.readObject() as TreeNode;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_childrenMap);
            output.writeObject(_data);
            output.writeObject(_parent);
        }
    }
}