/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openwms.common.util {

    import java.util.Iterator;

    [Bindable]
    [RemoteClass(alias="org.openwms.common.util.TreeNodeImpl")]
    public class TreeNodeImpl extends TreeNodeImplBase {

        override public function get children():Iterator {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get leaf():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }
    }
}