/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EntityServiceImpl.as).
 */

package org.openwms.common.service.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.apache.commons.logging.Log;
    import org.openwms.common.dao.GenericDao;
    import org.openwms.common.service.EntityService;

    [Bindable]
    public class EntityServiceImplBase implements IExternalizable, EntityService {

        private var _dao:GenericDao;
        private var _logger:Log;

        public function set dao(value:GenericDao):void {
            _dao = value;
        }

        public function readExternal(input:IDataInput):void {
            _dao = input.readObject() as GenericDao;
            _logger = input.readObject() as Log;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_dao);
            output.writeObject(_logger);
        }
    }
}