/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TransportServiceImpl.as).
 */

package org.openwms.common.service.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.apache.commons.logging.Log;
    import org.openwms.common.dao.GenericDao;
    import org.openwms.common.service.TransportService;

    [Bindable]
    public class TransportServiceImplBase implements IExternalizable, TransportService {

        private var _LOG:Log;
        private var _locationDao:GenericDao;
        private var _transportUnitDao:GenericDao;

        public function set locationDao(value:GenericDao):void {
            _locationDao = value;
        }

        public function set transportUnitDao(value:GenericDao):void {
            _transportUnitDao = value;
        }

        public function readExternal(input:IDataInput):void {
            _LOG = input.readObject() as Log;
            _locationDao = input.readObject() as GenericDao;
            _transportUnitDao = input.readObject() as GenericDao;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_LOG);
            output.writeObject(_locationDao);
            output.writeObject(_transportUnitDao);
        }
    }
}