/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.common.domain.units {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.common.domain.units.PieceUnit")]
    public class PieceUnit extends Enum {

        public static const PC:PieceUnit = new PieceUnit("PC", _);
        public static const DOZ:PieceUnit = new PieceUnit("DOZ", _);

        function PieceUnit(value:String = null, restrictor:* = null) {
            super((value || PC.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [PC, DOZ];
        }

        public static function valueOf(name:String):PieceUnit {
            return PieceUnit(PC.constantOf(name));
        }
    }
}