/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.core.domain.system {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.core.domain.system.PropertyScope")]
    public class PropertyScope extends Enum {

        public static const APPLICATION:PropertyScope = new PropertyScope("APPLICATION", _);
        public static const MODULE:PropertyScope = new PropertyScope("MODULE", _);
        public static const ROLE:PropertyScope = new PropertyScope("ROLE", _);
        public static const USER:PropertyScope = new PropertyScope("USER", _);

        function PropertyScope(value:String = null, restrictor:* = null) {
            super((value || APPLICATION.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [APPLICATION, MODULE, ROLE, USER];
        }

        public static function valueOf(name:String):PropertyScope {
            return PropertyScope(APPLICATION.constantOf(name));
        }
    }
}