/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TypeStackingRule.as).
 */

package org.openwms.common.domain {

    import flash.events.EventDispatcher;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import flash.utils.getQualifiedClassName;
    import mx.core.IUID;
    import mx.utils.UIDUtil;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;
    import org.granite.tide.IEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class TypeStackingRuleBase implements IExternalizable, IUID {

        protected var _em:IEntityManager = null;

        private var __initialized:Boolean = true;
        private var __detachedState:String = null;

        private var _allowedTransportUnitType:TransportUnitType;
        private var _id:Number;
        private var _noTransportUnits:int;
        private var _transportUnitType:TransportUnitType;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __initialized;

            var property:* = this[name];
            return (
                (!(property is TypeStackingRule) || (property as TypeStackingRule).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        [Transient]
        public function meta_getEntityManager():IEntityManager {
            return _em;
        }
        public function meta_setEntityManager(em:IEntityManager):void {
            _em = em;
        }

        public function get allowedTransportUnitType():TransportUnitType {
            return _allowedTransportUnitType;
        }

        public function get id():Number {
            return _id;
        }

        public function get noTransportUnits():int {
            return _noTransportUnits;
        }

        public function get transportUnitType():TransportUnitType {
            return _transportUnitType;
        }

        public function set uid(value:String):void {
            // noop...
        }
        public function get uid():String {
        	if (isNaN(_id))
        		return UIDUtil.createUID();
        	return getQualifiedClassName(this) + "#[" + String(_id) + "]";
        	
        }

        public function meta_merge(em:IEntityManager, obj:*):void {
            var src:TypeStackingRuleBase = TypeStackingRuleBase(obj);
            __initialized = src.__initialized;
            __detachedState = src.__detachedState;
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._allowedTransportUnitType, _allowedTransportUnitType, null, this, 'allowedTransportUnitType', function setter(o:*):void{_allowedTransportUnitType = o as TransportUnitType});
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number});
               em.meta_mergeExternal(src._noTransportUnits, _noTransportUnits, null, this, 'noTransportUnits', function setter(o:*):void{_noTransportUnits = o as int});
               em.meta_mergeExternal(src._transportUnitType, _transportUnitType, null, this, 'transportUnitType', function setter(o:*):void{_transportUnitType = o as TransportUnitType});
            }
            else {
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number});
            }
        }

        public function readExternal(input:IDataInput):void {
            __initialized = input.readObject() as Boolean;
            __detachedState = input.readObject() as String;
            if (meta::isInitialized()) {
                _allowedTransportUnitType = input.readObject() as TransportUnitType;
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _noTransportUnits = input.readObject() as int;
                _transportUnitType = input.readObject() as TransportUnitType;
            }
            else {
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__initialized);
            output.writeObject(__detachedState);
            if (meta::isInitialized()) {
                output.writeObject((_allowedTransportUnitType is IPropertyHolder) ? IPropertyHolder(_allowedTransportUnitType).object : _allowedTransportUnitType);
                output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id);
                output.writeObject((_noTransportUnits is IPropertyHolder) ? IPropertyHolder(_noTransportUnits).object : _noTransportUnits);
                output.writeObject((_transportUnitType is IPropertyHolder) ? IPropertyHolder(_transportUnitType).object : _transportUnitType);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}
