/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openwms.common.domain {

    [Bindable]
    [RemoteClass(alias="org.openwms.common.domain.TypePlacingRule")]
    public class TypePlacingRule extends TypePlacingRuleBase {
    }
}