/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED INTERFACE (GenericDao.as).
 */

package org.openwms.common.dao {

    import java.lang.Class;

    public interface GenericDaoBase {

        function set persistentClass(value:Class):void;
    }
}