/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED INTERFACE (TransportUnitDao.as).
 */

package org.openwms.common.dao {

    public interface TransportUnitDaoBase extends GenericDao {
    }
}