/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractGenericJpaDao.as).
 */

package org.openwms.common.dao.core {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import java.lang.Class;
    import org.openwms.common.dao.GenericDao;

    [Bindable]
    public class AbstractGenericJpaDaoBase implements IExternalizable, GenericDao {

        private var _persistentClass:Class;

        public function set persistentClass(value:Class):void {
            _persistentClass = value;
        }
        public function get persistentClass():Class {
            return _persistentClass;
        }

        public function readExternal(input:IDataInput):void {
            _persistentClass = input.readObject() as Class;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_persistentClass);
        }
    }
}