/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TransportUnitTypeDaoImpl.as).
 */

package org.openwms.common.dao.core {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.openwms.common.dao.TransportUnitTypeDao;

    [Bindable]
    public class TransportUnitTypeDaoImplBase extends AbstractGenericJpaDao implements TransportUnitTypeDao {


        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        }
    }
}