/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openwms.common.domain.values {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openwms.common.domain.values.LocationGroupState")]
    public class LocationGroupState extends Enum {

        public static const AVAILABLE:LocationGroupState = new LocationGroupState("AVAILABLE", _);
        public static const NOT_AVAILABLE:LocationGroupState = new LocationGroupState("NOT_AVAILABLE", _);

        function LocationGroupState(value:String = null, restrictor:* = null) {
            super((value || AVAILABLE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [AVAILABLE, NOT_AVAILABLE];
        }

        public static function valueOf(name:String):LocationGroupState {
            return LocationGroupState(AVAILABLE.constantOf(name));
        }
    }
}